baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: ssg-astro-craftcms
primary: true
siteGroup: 863cff4f-f659-488d-9614-5d2b915a50ee # astro-craftcms
sortOrder: 1
